In [26]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline, AutoModelForSequenceClassification
import torch

In [23]:
classifier = pipeline('sentiment-analysis')
classifier('We are very happy to show you the 🤗 Transformers library.')

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)


[{'label': 'POSITIVE', 'score': 0.9997795224189758}]

In [27]:
checkpoint = 'distilbert-base-uncased-finetuned-sst-2-english'
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

raw_inputs = ['We are very happy to show you the 🤗 Transformers library.',
              'We hope you don\'t hate it.',
              'We really hate it.']

tokenized_inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors='pt')

tokenized_inputs

Downloading: 100%|██████████| 268M/268M [00:25<00:00, 10.6MB/s] 


{'input_ids': tensor([[  101,  2057,  2024,  2200,  3407,  2000,  2265,  2017,  1996,   100,
         19081,  3075,  1012,   102],
        [  101,  2057,  3246,  2017,  2123,  1005,  1056,  5223,  2009,  1012,
           102,     0,     0,     0],
        [  101,  2057,  2428,  5223,  2009,  1012,   102,     0,     0,     0,
             0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]])}

In [6]:
tokenizer.convert_tokens_to_ids(tokenizer.tokenize(raw_inputs[0]))

[2057, 2024, 2200, 3407, 2000, 2265, 2017, 1996, 100, 19081, 3075, 1012]

In [3]:
encoded = [tokenizer.encode(raw_input, add_special_tokens=True) for raw_input in raw_inputs]
encoded

[[101,
  2057,
  2024,
  2200,
  3407,
  2000,
  2265,
  2017,
  1996,
  100,
  19081,
  3075,
  1012,
  102],
 [101, 2057, 3246, 2017, 2123, 1005, 1056, 5223, 2009, 1012, 102],
 [101, 2057, 2428, 5223, 2009, 1012, 102]]

In [23]:
tokenized = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors='pt')
input_ids = tokenized.input_ids
masks = tokenized.attention_mask

In [29]:
model(input_ids, attention_mask=masks).logits

tensor([[-4.0833,  4.3364],
        [ 0.0818, -0.0418],
        [ 4.1310, -3.4035]], grad_fn=<AddmmBackward0>)

In [30]:
model(input_ids).logits

tensor([[-4.0833,  4.3364],
        [ 1.6334, -1.4077],
        [ 3.5773, -3.0513]], grad_fn=<AddmmBackward0>)

In [75]:
logits = model(ids['input_ids'])
#convert logits to probabilities
import torch.nn.functional as F
#convert logits to probabilities
logits = logits.logits
probs = F.softmax(logits, dim=1)
probs

SequenceClassifierOutput(loss=None, logits=tensor([[-4.0833,  4.3364],
        [ 1.6334, -1.4077],
        [ 3.5773, -3.0513]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [83]:
tokens = [tokenizer.tokenize(raw_input) for raw_input in raw_inputs]
ids = [tokenizer.convert_tokens_to_ids(token) for token in tokens]

In [90]:
input_ids = torch.tensor([ids[0]])

In [91]:
model(input_ids)

SequenceClassifierOutput(loss=None, logits=tensor([[-3.4835,  3.7811]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [4]:
from transformers import AutoModel
model = AutoModel.from_pretrained(checkpoint)


Some weights of the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing DistilBertModel: ['classifier.weight', 'pre_classifier.weight', 'pre_classifier.bias', 'classifier.bias']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [14]:
outputs = model(**tokenized_inputs)

In [6]:
# find the shape of the outputs
print(outputs.last_hidden_state.shape)

torch.Size([3, 14, 768])


In [10]:
# convert a list of lists to a tensor of shape (1, len(list))
def list_to_tensor(list):
    return torch.tensor(list).unsqueeze(0)
    


In [ ]:
# loop through key value pairs in dictionary
for key, value in model_dict.items():
    # load tokenizer and model
    tokenizer = AutoTokenizer.from_pretrained(key)
    model = AutoModelForSeq2SeqLM.from_pretrained(value)
    # create summarization pipeline
    summarizer = pipeline("summarization", model=model, tokenizer=tokenizer)
    # summarize text
    summary = summarizer(text, max_length=100, min_length=30, do_sample=False)
    # print summary
    print(summary)

In [2]:
classifier = pipeline("zero-shot-classification", model="joeddav/xlm-roberta-large-xnli")
classifier('I am a student', candidate_labels=['teacher', 'student', 'engineer', 'lawyer'])


Downloading:   0%|          | 0.00/734 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.09G [00:00<?, ?B/s]

KeyboardInterrupt: 

In [5]:
classifier = pipeline('sentiment-analysis')
classifier('I am happy')

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)


[{'label': 'POSITIVE', 'score': 0.9998801946640015}]

In [ ]:
# get the ner pipeline for medical domain
classifier = pipeline('ner', model='dslim/bert-base-NER')

In [6]:
from bert_score import score

In [9]:
score(['This is a test'], ['This is great'], lang='en')

Some weights of the model checkpoint at roberta-large were not used when initializing RobertaModel: ['lm_head.decoder.weight', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.bias']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


(tensor([0.9349]), tensor([0.9280]), tensor([0.9314]))

In [10]:
from bert_score import BERTScorer